### ISSUE TITLE
Why is the Tick rate 10000Hz and not 1000Hz ?

### ISSUE THREAD

**Issue by pjalocha** [BriscoeTech/Arduino-FreeRTOS-SAMD21#1]
I tried the code and it worked fine for me except the tick rate was 10000Hz instead of "standard" 1000Hz. The Arduino delay() was as well off by a factor of 10. But when I set the tick rate to 1000 in the FreeRTOSConfig.h all came back to normal: both RTOS tick rate and the Arduino delay() so why not have it set at 1000 ?

**Comment by BriscoeTech** [comment]
Hello pjalocha,

Sorry for the late reply, better late than never right.

Thank you for finding that, I was wondering why the millis/micros/delays were off by a factor of 10. I updated the repository and they should all work properly again.

Thanks for posting!
