### ISSUE TITLE
FreeRTOS 10

### ISSUE THREAD

**Issue by sslupsky** [BriscoeTech/Arduino-FreeRTOS-SAMD21#2]
Any plans to update to FreeRTOS 10?

**Comment by Ve2mrx** [comment]
@sslupsky I'm also curious if there are nice benefits to a newer version...
Should I start porting to this version or wait?

**Comment by BriscoeTech** [comment]
Hello sslupsky and Ve2mrx,

Sorry for the late reply, I just discovered I was not subscribed to my own repo lol.

Yes, I definitely plan on porting everything to FreeRTOS 10, I am especially interested in the stream buffers, have afew projects in mind where they will be quite handy.

The next question is when will I do it hehehe. I will admit I am a man of many projects, and this one is on the todo list when I have some free time. The holidays are coming, I may find some time to sit down and make this happen.

**Comment by cheetor5923** [comment]
I have already ported some of the FreeRTOS 10 code into the a copy of this library I am using for a project at work, very little work (read as "None at all") was needed so far.  I'll see over the coming weeks if I can get together a more complete update

**Comment by BriscoeTech** [comment]
Hello cheetor5923

Thats great to hear! Looking forward to seeing your library when its done, and we can merge those changes in.

**Comment by drewfish** [comment]
I'm interested in this as well. If you'd like I can attempt a pull request.

**Comment by ardiri** [comment]
i did the process myself to support FreeRTOS 10.2.1

- grab sources from freertos.com
- grab the advanced software framework from atmel (they have freertos inside)

the latest ASF has FreeRTOS 10.0.0 - what you need is the Source/portable/GCC/ARM_CM0/* files and the appropriate heap_x.c from Source/portable/MemMang. the Sys callbacks need to be modified; specifically SysTick_Handler has already been defined by  Arduino; so need to hook into the sysTickHandler().. provide the application callbacks within some 'extern "C' { }' blocks and you are good to go.

**Comment by ardiri** [comment]
just need to create some symbolic links (i'm on mac) and the structure remains consistent for future updates as well. attached is a directory structure for the library. works perfectly.

<img width="300" alt="Screen Shot 2019-08-04 at 3 12 03 pm" src="https://user-images.githubusercontent.com/7701132/62424090-55c2f580-b6ca-11e9-853e-86c8aa39645c.png">

**Comment by trlafleur** [comment]
ardiri...
Have you posted your port yet??
github??

**Comment by ardiri** [comment]
no; as you can figure it out from downloading the freertos source and ASF sources and doing a merge as i've shown in the file directory structure.

**Comment by trlafleur** [comment]
Just thought it would save some time if there was a zip or github image

Thanks

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by ardiri** [comment]
GitHub doesn't support symbolic links unfortunately

**Comment by trlafleur** [comment]
can you send me a zip of the FGreeRTOS directory on your mac?? I also run a
mac...  that would be an easy way for me to get started....

tom@lafleur.us

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by BriscoeTech** [comment]
A looong overdue post, but better late than never right ;-)

The project is now using FreeRtos v10.2.1. I have been running it for quite afew months now and everything is very stable. Thank you again @drewfish and @trlafleur for your support!
