### ISSUE TITLE
error: unknown type name 'Stream'

### ISSUE THREAD

**Issue by r-valkenburg** [BriscoeTech/Arduino-FreeRTOS-SAMD21#23]
Hi there!

I downloaded and installed your latest version. I got an error when compiling the example "CompilerAndLinker_Test" from the Arduino IDE:

In file included from /home/robbie/Arduino/libraries/FreeRTOS_SAMD21/src/FreeRTOS_SAMD21.h:30,
                 from sketch/GameThing.h:1,
                 from sketch/GameThing.c:1:
Arduino/libraries/FreeRTOS_SAMD21/src/error_hooks.h:27:23: error: unknown type name 'Stream'
   27 |  void vSetErrorSerial(Stream *serial);
      |                       ^~~~~~
exit status 1
Error compiling for board Adafruit Feather M0.

**Comment by BriscoeTech** [comment]
Hello woodage,

Thanks for posting! I recently added some serial printing options to the error handler hooks and didn't think to re-run this project. Looks like some c code including this header did not like the new cpp serial objects. Oops!

I fixed the issue and pushed it to the development branch, will merge this to master soon.

Thanks again!
Scott
