### ISSUE TITLE
Missing "MemoryFree.h file

### ISSUE THREAD

**Issue by cedric-ak** [BriscoeTech/Arduino-FreeRTOS-SAMD21#27]
Hi guys

Great job on this library I really do like it. 
I've tried compiling basic example 2 I found that "MemoryFree.h" is missing from the src folder.

**Comment by BriscoeTech** [comment]
Hello cedric-ak,

Glad it is working well for you :-)

The comment section of the example has the link to the library, it is not a standard library and will have to be added to your arduino library folder.
https://github.com/mpflaga/Arduino-MemoryFree

Good luck!

**Comment by cedric-ak** [comment]
Thank you problem solved.
