### ISSUE TITLE
Misplaced extern "C" in FreeRTOS.h

### ISSUE THREAD

**Issue by pjalocha** [BriscoeTech/Arduino-FreeRTOS-SAMD21#3]
When compiling a more complex project, I noticed a problem of "template with C linkage"
and fixed it by moving the part:

#ifdef __cplusplus
extern "C" {
#endif

to the position after the:

#if( configUSE_MALLOC_FAILED_HOOK > 0 )
        void vApplicationMallocFailedHook(void);
#endif

**Comment by BriscoeTech** [comment]
Hello pjalocha,
Thank you for posting, this is really interesting. I haven't seen this problem in my projects yet, so I have some questions to track down why this is happening

* Do you have your source code files including FreeRTOS.h directly?
* Could you post a small snipit of your project so I can see where your includes are and in what file types?

Thanks!

**Comment by BriscoeTech** [comment]
Hello pjalocha,
I found the root problem and fixed it, it looks like a duplicate typedef you mentioned got added to the file. I commented out the duplicate entry, should work as expected now.
Thanks!
