### ISSUE TITLE
Missing MemoryFree.h file

### ISSUE THREAD

**Issue by esemese** [BriscoeTech/Arduino-FreeRTOS-SAMD21#6]
I am trying to build the Basic_RTOS_Example2 eample in Arduino IDE and get:
MemoryFree.h: No such file or directory.

I am using the version 1.8.8 of the IDE.

**Comment by BriscoeTech** [comment]
Hello esemese,

Sorry about that, I forgot that I have a library installed to give me the freeMemory() function call.

Install the library found here and that example will work fine
https://github.com/mpflaga/Arduino-MemoryFree

I will add a comment to the example explaining this and will push a updated example, thanks!

**Comment by esemese** [comment]
All working now. Thanks for the fast response and all the work to port this.
